# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: message.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'message.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmessage.proto\x12\x02im\"\xd0\x01\n\x0b\x43hatMessage\x12\n\n\x02id\x18\x01 \x01(\t\x12\x17\n\x0f\x63onversation_id\x18\x02 \x01(\t\x12\x11\n\tsender_id\x18\x03 \x01(\x03\x12\x0b\n\x03seq\x18\x04 \x01(\x03\x12\x0c\n\x04type\x18\x05 \x01(\x05\x12\x0f\n\x07\x63ontent\x18\x06 \x01(\t\x12\r\n\x05\x65xtra\x18\x07 \x01(\t\x12\x0e\n\x06status\x18\x08 \x01(\x05\x12\x12\n\ncreated_at\x18\t \x01(\t\x12\x13\n\x0bsender_name\x18\n \x01(\t\x12\x15\n\rsender_avatar\x18\x0b \x01(\t\"n\n\x12SendMessageRequest\x12\x17\n\x0f\x63onversation_id\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\x05\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12\r\n\x05\x65xtra\x18\x04 \x01(\t\x12\x11\n\tclient_id\x18\x05 \x01(\t\"-\n\nMessageAck\x12\x12\n\nmessage_id\x18\x01 \x01(\t\x12\x0b\n\x03seq\x18\x02 \x01(\x03\"\x90\x01\n\x12\x43onversationUpdate\x12\x17\n\x0f\x63onversation_id\x18\x01 \x01(\t\x12\x1c\n\x14last_message_preview\x18\x02 \x01(\t\x12\x17\n\x0flast_message_at\x18\x03 \x01(\t\x12\x14\n\x0cunread_count\x18\x04 \x01(\x05\x12\x14\n\x0ctotal_unread\x18\x05 \x01(\x05*7\n\x0bMessageType\x12\x08\n\x04TEXT\x10\x00\x12\t\n\x05IMAGE\x10\x01\x12\t\n\x05VIDEO\x10\x02\x12\x08\n\x04\x46ILE\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGETYPE']._serialized_start=538
  _globals['_MESSAGETYPE']._serialized_end=593
  _globals['_CHATMESSAGE']._serialized_start=22
  _globals['_CHATMESSAGE']._serialized_end=230
  _globals['_SENDMESSAGEREQUEST']._serialized_start=232
  _globals['_SENDMESSAGEREQUEST']._serialized_end=342
  _globals['_MESSAGEACK']._serialized_start=344
  _globals['_MESSAGEACK']._serialized_end=389
  _globals['_CONVERSATIONUPDATE']._serialized_start=392
  _globals['_CONVERSATIONUPDATE']._serialized_end=536
# @@protoc_insertion_point(module_scope)
